active_cabinet:
  name: ActiveCabinet
  summary: ActiveRecord-inspired interface for HashCabinet, the file-based key-object store
  lang: Ruby
  tags:
  - ruby
  - gem
  - ruby-developer-utilities

alf: 
  name: Alf
  summary: Alias manager for Bash
  lang: Bash
  tags:
  - bash
  - cli
  - alias-management
  - shell-productivity

apicake:
  name: API Cake
  summary: Build dynamic API wrappers
  lang: Ruby
  tags:
  - ruby
  - gem
  - api

approvals.bash:
  name: Approvals.bash
  summary: Bash Interactive Approval Testing
  lang: Bash
  tags:
  - bash
  - testing-tools

audio_addict:
  name: AudioAddict
  summary: AudioAddict command line for voting and playlist management
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - audio-tools

bashly:
  name: Bashly
  summary: Bash command line framework and CLI Generator
  lang: Ruby
  tags:
  - ruby
  - gem
  - bash
  - shell-productivity
  - cli-tools
  - cli

bobkit:
  name: Bobkit
  summary: Site generation toolkit with Slim, SCSS, CoffeeScript and Markdown
  lang: Ruby
  tags:
  - ruby
  - gem
  - site-building

clicumber:
  name: Clicumber
  summary: Cucumber step definitions for testing command line applications
  lang: Gherkin
  tags:
  - gherkin
  - cucumber
  - testing-tools

clipper:
  name: Clipper
  summary: Pure command line arguments parser
  lang: Crystal
  tags:
  - crystal
  - cli-tools

colorly:
  name: Colorly
  summary: Command line and DSL for generating color palettes
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli

colsole:
  name: Colsole
  summary: Utility functions for colorful console applications with Ruby
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli-tools

completely:
  name: Completely
  summary: Generate bash completion scripts using a simple configuration file
  lang: Ruby
  tags:
  - ruby
  - gem
  - bash
  - shell-productivity
  - cli-tools
  - cli

concode:
  name: Concode
  summary: Generate consistent-codenames from any string (Heroku style, aka Haiku).
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - ruby-developer-utilities
  - name-utilities

configly:
  name: Configly
  summary: Minimal, lightweight, multi-YAML settings library with dot notation.
  lang: Ruby
  tags:
  - ruby
  - gem
  - configuration-tools
  - ruby-developer-utilities

datamix:
  name: DataMix
  summary: DSL for manipulating tabular data
  lang: Ruby
  tags:
  - ruby
  - gem
  - data-processing

docker-alpine-adsf:
  name: Docker Alpine ADSF
  summary: Ruby ADSF file server on Alpine linux
  lang: Dockerfile
  tags:
  - docker
  - alpine
  - ruby
  - web-server

docker-alpine-crystal:
  name: Docker Alpine Crystal
  summary: Alpine image with the Crystal programming language
  lang: Dockerfile
  tags:
  - docker
  - alpine
  - crystal

docker-alpine-mongo:
  name: Docker Alpine Mongo
  summary: MongoDB on Alpine linux
  lang: Dockerfile
  tags:
  - docker
  - alpine
  - mongo

docker-alpine-php:
  name: Docker Alpine PHP
  summary: PHP CLI on Alpine linux
  lang: Dockerfile
  tags:
  - docker
  - alpine
  - php

docker-alpine-ruby:
  name: Docker Alpine Ruby
  summary: Minimal Ruby docker image with native extensions support
  lang: Dockerfile
  tags:
  - docker
  - alpine
  - ruby

docker-alpine-ruby-mongo:
  name: Docker Alpine Ruby Mongo
  summary: Docker image with ruby and mongo tools based on Alpine
  lang: Dockerfile
  tags:
  - docker
  - alpine
  - ruby
  - mongo

docker-borg-client:
  name: Docker Borg Client
  summary: Docker image with Borg Backup client
  lang: Dockerfile
  tags:
  - docker
  - devops

docker-fallback:
  name: Docker Fallback
  summary: Default ingress backend
  lang: Dockerfile
  tags:
  - docker
  - web-server
  - devops

docker-git-compose:
  name: Docker Git Compose
  summary: Docker image with docker, git and docker-compose
  lang: Dockerfile
  tags:
  - docker
  - git
  - cicd

docker-gotty:
  name: Docker Gotty
  summary: Docker image with browser based linux terminal
  lang: Dockerfile
  tags:
  - docker

docker-gotty-ruby:
  name: Docker Gotty Ruby
  summary: Docker image with browser based linux terminal and Ruby
  lang: Dockerfile
  tags:
  - docker
  - ruby

docker-jobly:
  name: Docker Jobly
  summary: Docker image with the Jobly job server
  lang: Dockerfile
  tags:
  - docker
  - ruby
  - background-jobs
  - cicd

docker-madness:
  name: Docker Madness
  summary: Madness instant markdown server
  lang: Dockerfile
  tags:
  - docker
  - markdown
  - documentation-server

docker-mdbook:
  name: Docker MDBook
  summary: Docker with mdbook site generator
  lang: Dockerfile
  tags:
  - docker
  - markdown
  - documentation-server

docker-rabbit:
  name: Docker Rabbit
  summary: RabbitMQ image with extras
  lang: Dockerfile
  tags:
  - docker
  - rabbit

docker-redirector:
  name: Docker Redirector
  summary: Docker image to handle domain redirects
  lang: Dockerfile
  tags:
  - docker
  - web-server
  - devops

docker-ruby-python:
  name: Docker Ruby Python
  summary: Docker image with Ruby and Python 2+3 on Alpine
  lang: Dockerfile
  tags:
  - docker
  - alpine

docker-snapcrawl:
  name: Docker Snapcrawl
  summary: Crawl a website and take screenshots (Docker version)
  lang: Dockerfile
  tags:
  - docker
  - ruby
  - site-analyzers

docker-sshd:
  name: Docker SSHD
  summary: Alpine SSH Client and Server
  lang: Dockerfile
  tags:
  - docker
  - alpine
  - ssh
  - devops

docker-ubuntu:
  name: Docker Ubuntu
  summary: Ubuntu sandbox with non-root user
  lang: Dockerfile
  tags:
  - docker
  - ubuntu

docspec:
  name: Docspec
  summary: Inline tests in Markdown documents
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - testing-tools
  - ruby-developer-utilities

echo-webserver:
  name: Echo Webserver
  summary: A web server that echoes the request information back
  lang: Ruby
  tags:
  - ruby
  - web-server
  - docker
  - api

eclipse:
  name: Eclipse
  summary: Encrypt / decrypt any text with a simple hotkey
  lang: AutoHotkey
  tags:
  - autohotkey
  - encryption

enforce:
  name: Enforce
  summary: DSL for verifying file/folder content
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli

eod:
  name: EOD Historical Data
  summary: Library and command line interface for EOD Historical Data API
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - api
  - data-service

erbx:
  name: ERBX
  summary: ERB Extended with Pretty Tags
  lang: Ruby
  tags:
  - ruby
  - gem
  - ruby-developer-utilities
  - templating

extended_yaml:
  name: ExtendedYAML
  summary: Load YAML files that call other YAML files
  lang: Ruby
  tags:
  - ruby
  - gem
  - configuration-tools
  - ruby-developer-utilities

filecache:
  name: Filecache
  summary: File caching library for Go
  lang: Go
  tags:
  - go
  - cache

FlicFlac:
  name: FlicFlac
  summary: Tiny portable audio converter for Windows 
  lang: AutoHotkey
  tags:
  - autohotkey
  - audio-tools

fredric:
  name: Fredric
  summary: FRED API library and command line interface
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - api
  - data-service

fuzzy-cd: 
  name: Fuzzy CD
  summary: Change directories with fuzzy search
  lang: Bash
  tags:
  - bash
  - cli
  - shell-productivity

getcomments:
  name: GetComments
  summary: Extract comments from Ruby code
  lang: Ruby
  tags:
  - ruby
  - gem
  - ruby-developer-utilities

"git-changelog":
  name: git-changelog
  summary: Generate change logs from git repositories
  lang: Bash
  tags:
  - bash
  - cli
  - git

gondl:
  name: Gondl
  summary: Command line console for Quandl
  lang: Go
  tags:
  - go
  - cli
  - api
  - data-service

Gridy:
  name: Gridy
  summary: Snap windows to grid
  lang: AutoHotkey
  tags:
  - autohotkey

gtx:
  name: GTX
  summary: Minimal Template Engine
  lang: Ruby
  tags:
  - ruby
  - gem
  - ruby-developer-utilities
  - templating

hash_cabinet:
  name: HashCabinet
  summary: File-based, key-object store with hash-like access
  lang: Ruby
  tags:
  - ruby
  - gem
  - cache
  - ruby-developer-utilities

httpme:
  name: HTTPMe
  summary: Static files web server with basic authentication
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - docker
  - web-server

icodi:
  name: Icodi
  summary: Deterministic Random SVG Icon Generator
  lang: Ruby
  tags:
  - ruby
  - gem
  - svg

icodi-site:
  name: Icodi Playground
  summary: Deterministic Random SVG Icon Generator (Online Demo)
  lang: Ruby
  tags:
  - ruby
  - web-server
  - svg

intrinio:
  name: Intrinio
  summary: Library and command line interface for Intrinio data API
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - api
  - data-service

ismine:
  name: IsMine
  summary: Ruby command line domain checker with wildcards
  lang: Ruby
  tags:
  - ruby
  - cli
  - name-utilities
  - domain-utilities

jekyll-theme-proxima:
  name: Jekyll Theme Proxima
  summary: Theme for GitHub Pages, with GitHub-like styling
  lang: HTML
  tags:
  - html
  - jekyll
  - site-building
  - github

jobly:
  name: Jobly
  summary: Compact job server with API, CLI, Web UI and a Sidekiq heart
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - api
  - background-jobs
  - web-server
  - cicd

jossh:
  name: Jossh
  summary: Run local scripts remotely by SSH
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - ssh
  - devops

kojo:
  name: Kojo
  summary: Command line utility for generating config files from templates and definition files
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - templating
  - configuration-tools

lightly:
  name: Lightly
  summary: Ruby file cache for performing heavy tasks lightly
  lang: Ruby
  tags:
  - ruby
  - gem
  - cache

loadrunner:
  name: LoadRunner
  summary: GitHub webhook server and event simulator
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - web-server
  - github
  - devops
  - cicd

lp:
  name: Lovely Print
  summary: Print any object in YAML format
  lang: Ruby
  tags:
  - ruby
  - gem
  - ruby-developer-utilities

madman:
  name: Madman
  summary: The markdown swiss army knife
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - markdown

madness:
  name: Madness
  summary: Instant markdown server
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - markdown
  - documentation-server

menu_commander:
  name: Menu Commander
  summary: Create menus for any command line tool using simple YAML configuration
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - shell-productivity

minichart:
  name: Minichart
  summary: Genearte SVG charts with Ruby
  lang: Ruby
  tags:
  - ruby
  - gem
  - svg

mister_bin:
  name: Mister Bin
  summary: Build modular command line tools
  lang: Ruby
  tags:
  - ruby
  - gem
  - ruby-developer-utilities
  - cli-tools

opcode: 
  name: Opcode
  summary: Local command shortcuts
  lang: Bash
  tags:
  - bash
  - alias-management
  - shell-productivity

php-quandl:
  name: PHP Quandl
  summary: Easy access to the Quandl Data API using PHP
  lang: PHP
  tags:
  - php
  - api
  - data-service

pobject:
  name: Persistent Object
  summary: Automatically persist objects to disk as YAML files
  lang: Ruby
  tags:
  - ruby
  - gem
  - cache

pretty_trace:
  name: Pretty Trace
  summary: Make your Ruby backtrace pretty again
  lang: Ruby
  tags:
  - ruby
  - gem
  - ruby-developer-utilities

pundit_extra:
  name: Pundit Extra
  summary: Extensions and helpers for Pundit authorization library
  lang: Ruby
  tags:
  - ruby
  - gem
  - rails
  - authorization

quandl:
  name: Quandl
  summary: Go library for accessing Quandl API
  lang: Go
  tags:
  - go
  - api

quata:
  name: Quata
  summary: Lightweight Quandl API library and command line interface
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - api
  - data-service

recode:
  name: Recode
  summary: Command line refactoring utility
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - ruby-developer-utilities

redirectly:
  name: Redirectly
  summary: Redirect server with dynamic URL and hostname support
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - docker
  - web-server
  - devops

requires:
  name: Requires
  summary: Ruby's missing function to require all files and directories
  lang: Ruby
  tags:
  - ruby
  - gem
  - ruby-developer-utilities

rigit:
  name: Rig It
  summary: Build project templates easily without writing code
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - scaffolding
  - templating

rspec_approvals:
  name: RSpec Approvals
  summary: Interactive approval testing for RSpec
  lang: Ruby
  tags:
  - ruby
  - gem
  - rspec
  - ruby-developer-utilities
  - testing-tools

runfile:
  name: Runfile
  summary: Command line for your projects
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - ruby-developer-utilities
  - shell-productivity

rush-cli:
  name: Rush
  summary: Personal package manager
  lang: Bash
  tags:
  - bash
  - shell-productivity
  - package-management
  - devops

secret_hub:
  name: SecretHub
  summary: Manage GitHub secrets over multiple repositories
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - cicd
  - github

sasstool:
  name: Sasstool
  summary: Sass command line renderer
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - site-building
  - ruby-developer-utilities

sla:
  name: Site Link Analyzer
  summary: Command line broken links checker
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - site-analyzers

slacktail:
  name: Slacktail
  summary: Follow your Slack chats from the terminal
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - devops

snapcrawl:
  name: Snapcrawl
  summary: Crawl a website and take screenshots
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - site-analyzers

sting:
  name: Sting
  summary: Minimal, lightweight, multi-YAML settings library
  lang: Ruby
  tags:
  - ruby
  - gem
  - configuration-tools
  - ruby-developer-utilities

stress-server:
  name: Stress Server
  summary: Docker image for simulating server resource stress
  lang: Ruby
  tags:
  - ruby
  - docker
  - devops
  - web-server

super_docopt:
  name: Super Docopt
  summary: docopt-based command line utility builder
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli-tools

victor:
  name: Victor
  summary: Genearte SVG images by writing Ruby code
  lang: Ruby
  tags:
  - ruby
  - gem
  - svg

victor-cli:
  name: Victor CLI
  summary: Command line for Victor, the Ruby SVG library
  lang: Ruby
  tags:
  - ruby
  - gem
  - svg
  - cli

voicemaker:
  name: Voicemaker TTS API and CLI
  summary: Library and command line interface for Voicemaker Text-to-Speech API
  lang: Ruby
  tags:
  - ruby
  - gem
  - cli
  - api
  - audio-tools

WallpaperRandomizer:
  name: Wallpaper Randomizer
  summary: System tray wallpaper changer
  lang: AutoHotkey
  tags:
  - autohotkey

webcache:
  name: Webcache
  summary: Hassle-free caching for HTTP download with ruby
  lang: Ruby
  tags:
  - ruby
  - gem
  - cache
  - ruby-developer-utilities

wordscan:
  name: Wordscan
  summary: Dictionary and thesaurus regular expression search
  lang: Ruby
  tags:
  - ruby
  - cli
  - name-utilities

yamlcon:
  name: YAMLCon
  summary: YAML configuration file loader with dot notation support
  lang: Ruby
  tags:
  - ruby
  - gem
  - configuration-tools
  - ruby-developer-utilities

