accessibility: Accessibility
ai: AI
alias-management: Shell Alias Management
alpine: Alpine Linux
api-wrapper: API Wrapper
api: API
audio-tools: Audio Tools
authorization: Authorization
autohotkey: AutoHotkey
autoit: AutoIt
background-jobs: Background Jobs
bash: Bash
cache: Cache Management
cicd: CI/CD
cli-tools: CLI Tools
cli: CLI
configuration-tools: Configuration Tools
crystal: Crystal
cucumber: Cucumber
data-processing: Data Processing
devops: DevOps
docker-compose: Docker Compose
docker: Docker
documentation-server: Documentation Server
domain-utilities: Domain Utilities
encryption: Encryption
file-server: File Server
financial-data: Financial Data
gem: Ruby Gem
gherkin: Gherkin
git: Git
github: GitHub
go: Go
hcl: HCL
html: HTML
jekyll: Jekyll
markdown: Markdown
mongo: MongoDB
name-utilities: Name Utilities
package-management: Package Management
packer: Packer
php: PHP
rabbit: RabbitMQ
rails: Rails
rspec: RSpec
rubocop: Rubocop
ruby-developer-utilities: Ruby Developer Utilities
ruby: Ruby
scaffolding: Scaffolding
shell-productivity: Shell Productivity
site-analyzers: Site Analyzers
site-building: Site Building Tools
ssh: SSH
svg: SVG
templating: Templating
testing-tools: Testing Tools
tts: Text-to-Speech
ubuntu: Ubuntu
virtualization: Virtualization
web-server: Web Server
windows: Windows
